# 포트번호
server:
  port: 8060

# 뷰
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # 마이바티스 dataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cghfa7twoqzg.ap-northeast-2.rds.amazonaws.com/istudy_db?characterEncoding=utf-8
    username: admin
    password: root1234
  # 서버 자동 시작
  devtools:
    livereload:
      enabled: true
  # multipart 설정
  servlet:
    multipart:
      location: C:\\IsTudy\\istudy\\src\\main\\webapp\\
      enabled: true
      max-file-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: istudyjoin@gmail.com
    password: welcome2@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # mybatis에서 패키지를 생략할 수 있도록 설정 
mybatis:
    type-aliases-package: com.hot6.project.vo
    mapper-locations: mapper/*Mapper.xml
   
      
      
      
      
      
      